[package]
name = "s20_net_lib"
version = "0.1.0"
edition = "2021"

[dependencies]
eframe = "0.30.0"
egui = "0.30.0"  
chrono = "0.4"
winapi = { version = "0.3.9", features = ["winuser", "windef"] }
rand = "0.8"